export const taxMock = {
    name: "Lena Miras",
    taxId: "AUR-88-2219",
    year: 2032,
    status: "COMPLETED",

    federal: 15200,
    state: 8300,
    city: 2100,
    total: 15200 + 8300 + 2100,

    records: [
        {
            month: "2032-01",
            amount: 1800,
            type: "federal",
            status: "COMPLETED",
            note: "Auto-settled",
        },
        {
            month: "2032-02",
            amount: 1750,
            type: "state",
            status: "COMPLETED",
            note: "",
        },
        {
            month: "2032-03",
            amount: 220,
            type: "city",
            status: "PENDING",
            note: "Awaiting municipal confirmation",
        },
        {
            month: "2032-04",
            amount: 1850,
            type: "federal",
            status: "UNDER_REVIEW",
            note: "Automatic audit due to inter-state employment change",
        },
        {
            month: "2032-05",
            amount: 1680,
            type: "state",
            status: "COMPLETED",
            note: "",
        },
        {
            month: "2032-06",
            amount: 230,
            type: "city",
            status: "COMPLETED",
            note: "Real-time settlement",
        },
        {
            month: "2032-07",
            amount: 1900,
            type: "federal",
            status: "REFUND",
            note: "Refund triggered due to overpayment",
        },
        {
            month: "2032-08",
            amount: 1720,
            type: "state",
            status: "COMPLETED",
            note: "",
        },
        {
            month: "2032-09",
            amount: 210,
            type: "city",
            status: "COMPLETED",
            note: "",
        },
        {
            month: "2032-10",
            amount: 1810,
            type: "federal",
            status: "COMPLETED",
            note: "",
        },
        {
            month: "2032-11",
            amount: 1650,
            type: "state",
            status: "PENDING",
            note: "Employer delayed declaration",
        },
        {
            month: "2032-12",
            amount: 230,
            type: "city",
            status: "COMPLETED",
            note: "Final settlement of the year",
        },
    ],
};
